if (WIN32)
    set(FFMPEG_INCLUDE_PATH ${CMAKE_SOURCE_DIR}/thirdparty/windows/ffmpeg/include)
    set(FFMPEG_LIBRARY_PATH ${CMAKE_SOURCE_DIR}/thirdparty/windows/ffmpeg/lib)
else ()
    set(FFMPEG_INCLUDE_PATH ${CMAKE_SOURCE_DIR}/thirdparty/ffmpeg/build/include)
    set(FFMPEG_LIBRARY_PATH ${CMAKE_SOURCE_DIR}/thirdparty/ffmpeg/build/lib)
endif()
find_library(FFMPEG_LIBAVCODEC avcodec REQUIRED HINTS ${FFMPEG_LIBRARY_PATH})
find_library(FFMPEG_LIBAVDEVICE avdevice REQUIRED HINTS ${FFMPEG_LIBRARY_PATH})
find_library(FFMPEG_LIBAVFILTER avfilter REQUIRED HINTS ${FFMPEG_LIBRARY_PATH})
find_library(FFMPEG_LIBAVFORMAT avformat REQUIRED HINTS ${FFMPEG_LIBRARY_PATH})
find_library(FFMPEG_LIBAVUTIL avutil REQUIRED HINTS ${FFMPEG_LIBRARY_PATH})
find_library(FFMPEG_LIBPOSTPROC postproc REQUIRED HINTS ${FFMPEG_LIBRARY_PATH})
find_library(FFMPEG_SWRESAMPLE swresample REQUIRED HINTS ${FFMPEG_LIBRARY_PATH})
find_library(FFMPEG_SWSCALE swscale REQUIRED HINTS ${FFMPEG_LIBRARY_PATH})

set(FFMPEG_INCLUDE_DIRS ${FFMPEG_INCLUDE_PATH})
set(FFMPEG_LIBRARY_DIRS ${FFMPEG_LIBRARY_PATH})
set(FFMPEG_LIBRARIES ${FFMPEG_LIBAVCODEC}
                     ${FFMPEG_LIBAVDEVICE}
                     ${FFMPEG_LIBAVFILTER}
                     ${FFMPEG_LIBAVFORMAT}
                     ${FFMPEG_LIBAVUTIL}
                     ${FFMPEG_LIBPOSTPROC}
                     ${FFMPEG_SWRESAMPLE}
                     ${FFMPEG_SWSCALE})
