set(GTEST_INCLUDE_PATH ${CMAKE_SOURCE_DIR}/thirdparty/${OS_TYPE}/gtest/googletest/include)
set(GTEST_LIBRARY_PATH ${CMAKE_SOURCE_DIR}/thirdparty/${OS_TYPE}/gtest/build/lib)

find_library(GTEST_LIBGMOCK NAMES gmock REQUIRED HINTS ${GTEST_LIBRARY_PATH})
find_library(GTEST_LIBGMOCKMAIN NAMES gmock_main REQUIRED HINTS ${GTEST_LIBRARY_PATH})
find_library(GTEST_LIBGTEST NAMES gtest REQUIRED HINTS ${GTEST_LIBRARY_PATH})
find_library(GTEST_LIBGTEST_MAIN NAMES gtest_main REQUIRED HINTS ${GTEST_LIBRARY_PATH})

set(GTEST_INCLUDE_DIRS ${GTEST_INCLUDE_PATH})
set(GTEST_LIBRARY_DIRS ${GTEST_LIBRARY_PATH})
set(GTEST_LIBRARIES ${GTEST_LIBGMOCK}
                    ${GTEST_LIBGMOCKMAIN}
                    ${GTEST_LIBGTEST}
                    ${GTEST_LIBGTEST_MAIN})

add_library(GTEST::gmock IMPORTED INTERFACE)
set_target_properties(GTEST::gmock PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${GTEST_INCLUDE_DIRS}
    INTERFACE_LINK_LIBRARIES ${GTEST_LIBGMOCK})

add_library(GTEST::gmock_main IMPORTED INTERFACE)
set_target_properties(GTEST::gmock_main PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${GTEST_INCLUDE_DIRS}
    INTERFACE_LINK_LIBRARIES ${GTEST_LIBGMOCKMAIN})

add_library(GTEST::gtest IMPORTED INTERFACE)
set_target_properties(GTEST::gtest PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${GTEST_INCLUDE_DIRS}
    INTERFACE_LINK_LIBRARIES ${GTEST_LIBGTEST})

add_library(GTEST::gtest_main IMPORTED INTERFACE)
set_target_properties(GTEST::gtest_main PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${GTEST_INCLUDE_DIRS}
    INTERFACE_LINK_LIBRARIES ${GTEST_LIBGTEST_MAIN})
